# Generated by Django 3.2.6 on 2022-02-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Ключ')),
                ('ip', models.GenericIPAddressField(editable=False, null=True, verbose_name='IP адрес')),
                ('browser_family', models.CharField(editable=False, max_length=255, null=True, verbose_name='Браузер')),
                ('browser_version', models.CharField(editable=False, max_length=255, null=True, verbose_name='Версия браузера')),
                ('os_family', models.CharField(editable=False, max_length=255, null=True, verbose_name='Операционная система')),
                ('os_version', models.CharField(editable=False, max_length=255, null=True, verbose_name='Версия операционной системы')),
                ('device_family', models.CharField(editable=False, max_length=255, null=True, verbose_name='Устройство')),
                ('device_brand', models.CharField(editable=False, max_length=255, null=True, verbose_name='Бренд устройства')),
                ('device_model', models.CharField(editable=False, max_length=255, null=True, verbose_name='Модель устройства')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Токен',
                'verbose_name_plural': 'Токены',
                'ordering': ('-created_at',),
            },
        ),
    ]
